// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mangaDatabase.Service.Context;

namespace fullstackapi2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200501073522_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mangaDatabase.Models.UserInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("UserInfoSql");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Password = "password",
                            UserName = "maaoruzketo"
                        });
                });

            modelBuilder.Entity("mangaDatabase.Models.mangaFavorites", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bookCover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mangaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mangaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("mangaFavoritesSql");

                    b.HasData(
                        new
                        {
                            id = 1,
                            bookCover = "https://cdn.mangaeden.com/mangasimg/b0/b0ac7f12d2cb0fc07b9418d5544a3f97cbbc30e967396ae70f98d101.png",
                            mangaId = "4e70ea10c092255ef7004aa2",
                            mangaName = "One Piece",
                            userName = "maaoruzketo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
